### PR TITLE
feat(readme.md): add icons download link

### PR DESCRIPTION
**Pull request by rafamancan**
Add icons on README.md

## Icon Theme

`mkdir ~/.icons` if not exists

Download and extract [this link](https://github.com/dracula/gtk/files/5214870/Dracula.zip) on `~/.icons` folder

### CODE REVIEW

**Comment by mothinx** [comment]
In my case i had to extract link on /usr/shared/icons/Dracula/

**Comment by EliverLara** [comment]
Hi, @rafamancan, that's a nice addition, it would be great if you could put those instructions inside  the INSTALL.md file.

**Comment by rafamancan** [comment]
@mothinx done!
@EliverLara done!
If you have any suggestion, let me know.
[]s

**Comment by rafamancan** [comment]
image

**Comment by EliverLara** [comment]
Thanks @rafamancan, now it looks great!

**Pull request merged**
